string(JSON compiler_url GET "${PROTO_LOCK}" tools glslang url)
string(JSON compiler_hash GET "${PROTO_LOCK}" tools glslang sha256)
set(PROTO_GLSLANG "${PROTO_CACHE}/tools/glslang-16.5.0/bin/glslang.exe")
if(NOT EXISTS "${PROTO_GLSLANG}")
    file(MAKE_DIRECTORY "${PROTO_CACHE}/downloads")
    set(archive "${PROTO_CACHE}/downloads/glslang.zip")
    if(NOT EXISTS "${archive}")
        message(STATUS "Downloading pinned glslang 16.5.0 (13 MB)")
        file(DOWNLOAD "${compiler_url}" "${archive}" EXPECTED_HASH "SHA256=${compiler_hash}" TLS_VERIFY ON STATUS result)
        list(GET result 0 code)
        if(NOT code EQUAL 0)
            message(FATAL_ERROR "glslang download failed: ${result}")
        endif()
    endif()
    file(SHA256 "${archive}" actual_hash)
    if(NOT actual_hash STREQUAL compiler_hash)
        message(FATAL_ERROR "glslang archive hash mismatch: ${archive}")
    endif()
    file(ARCHIVE_EXTRACT INPUT "${archive}" DESTINATION "${PROTO_CACHE}/tools/glslang-16.5.0")
endif()
execute_process(COMMAND "${PROTO_GLSLANG}" --version RESULT_VARIABLE compiler_result OUTPUT_VARIABLE compiler_version ERROR_VARIABLE compiler_error)
if(NOT compiler_result STREQUAL "0" OR NOT compiler_version MATCHES "16\.5\.0")
    message(FATAL_ERROR "Pinned glslang could not run (${compiler_result}). Requires Windows UCRT, MSVCP140.dll, VCRUNTIME140.dll, VCRUNTIME140_1.dll. No runtime or Python is installed automatically. ${compiler_error}")
endif()
message(STATUS "glslang 16.5.0 preflight passed")

function(proto_shader input)
    file(GLOB shader_includes CONFIGURE_DEPENDS "${PROJECT_SOURCE_DIR}/shaders/*.glsl")
    get_filename_component(name "${input}" NAME)
    set(output "${CMAKE_BINARY_DIR}/bin/shaders/${name}.spv")
    add_custom_command(OUTPUT "${output}"
        COMMAND "${CMAKE_COMMAND}" -E make_directory "${CMAKE_BINARY_DIR}/bin/shaders"
        # Explicit discard semantics avoid requiring the optional demote feature for MASK.
        COMMAND "${PROTO_GLSLANG}" -V --target-env vulkan1.3 --discard-is-terminate "-I${PROJECT_SOURCE_DIR}/shaders" "${input}" -o "${output}"
        DEPENDS "${input}" "${PROTO_GLSLANG}" ${shader_includes} VERBATIM)
    set(PROTO_SHADERS ${PROTO_SHADERS} "${output}" PARENT_SCOPE)
endfunction()
